version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_NAME=${APP_NAME}
      - APP_IP=${APP_IP}
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    depends_on:
      - db_postgresql
      - minio
    networks:
      - app_network

  db_postgresql:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app_network

  minio:
    image: minio/minio
    restart: always
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER={S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD={S3_SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS={S3_BUCKET_NAME}
    ports:
      - ${S3_PORT}:${S3_PORT}
      - ${S3_CONSOLE_PORT}:${S3_CONSOLE_PORT}
    command: server /data --console-address ":{S3_CONSOLE_PORT}"
    depends_on:
      - db_postgresql
    networks:
      - app_network


volumes:
  postgres_data:
  minio_data:

networks:
  app_network: