"""ref_uniq_ci_v2

Revision ID: 02203b1e2f5d
Revises: c29e33008cb5
Create Date: 2025-03-10 23:52:06.535006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02203b1e2f5d'
down_revision: Union[str, None] = 'c29e33008cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_image_image_uuid_image_url_key', 'car_image', type_='unique')
    op.create_unique_constraint(None, 'car_image', ['image_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_image', type_='unique')
    op.create_unique_constraint('car_image_image_uuid_image_url_key', 'car_image', ['image_uuid', 'image_url'])
    # ### end Alembic commands ###
