"""ref_car_model

Revision ID: 3458e5ba1dae
Revises: 99fbc797b588
Create Date: 2025-03-13 20:03:33.451925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3458e5ba1dae'
down_revision: Union[str, None] = '99fbc797b588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE car_status_enum AS ENUM ('on_order', 'in_stock', 'in_transit');")
    op.add_column('car',
                  sa.Column('status', sa.Enum('on_order', 'in_stock', 'in_transit', name='car_status_enum'),
                            nullable=True))

    op.execute("UPDATE car SET status = 'on_order' WHERE status IS NULL;")
    op.alter_column('car', 'status',
                    existing_type=sa.Enum('on_order', 'in_stock', 'in_transit', name='car_status_enum'),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'status')
    # ### end Alembic commands ###
