"""ref_car_model_v5

Revision ID: bce7c0811914
Revises: 96ae6a7f7fbe
Create Date: 2025-03-19 17:43:13.768038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce7c0811914'
down_revision: Union[str, None] = '96ae6a7f7fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('acceleration', sa.Numeric(precision=3, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'acceleration')
    # ### end Alembic commands ###
