"""ref_carImage

Revision ID: 866760fcd31f
Revises: 6f07c5027cf9
Create Date: 2025-09-16 13:25:03.813663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866760fcd31f'
down_revision: Union[str, None] = '6f07c5027cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_image', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_image', 'created_at')
    # ### end Alembic commands ###
