"""ref_car_image_uuid

Revision ID: dddc9f7907a1
Revises: 0ce7f8028b65
Create Date: 2025-03-06 21:26:01.059787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dddc9f7907a1'
down_revision: Union[str, None] = '0ce7f8028b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
