"""ref_car_model_v4

Revision ID: 96ae6a7f7fbe
Revises: ca65436d22ba
Create Date: 2025-03-19 17:35:58.794076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ae6a7f7fbe'
down_revision: Union[str, None] = 'ca65436d22ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('drivetrain', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'drivetrain')
    # ### end Alembic commands ###
