"""ref_uniq_ci_v3

Revision ID: 99fbc797b588
Revises: 8539c3167c4e
Create Date: 2025-03-11 16:55:35.098363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99fbc797b588'
down_revision: Union[str, None] = '8539c3167c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_image_image_uuid_car_id_is_main_key', 'car_image', type_='unique')
    op.create_index('idx_unique_main_image_per_car', 'car_image', ['car_id'], unique=True, postgresql_where=sa.text('is_main IS true'))
    op.create_unique_constraint('uq_image_uuid_car', 'car_image', ['image_uuid', 'car_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_image_uuid_car', 'car_image', type_='unique')
    op.drop_index('idx_unique_main_image_per_car', table_name='car_image', postgresql_where=sa.text('is_main IS true'))
    op.create_unique_constraint('car_image_image_uuid_car_id_is_main_key', 'car_image', ['image_uuid', 'car_id', 'is_main'])
    # ### end Alembic commands ###
