"""ref_car_model_add

Revision ID: ca65436d22ba
Revises: 3458e5ba1dae
Create Date: 2025-03-19 16:44:56.531908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca65436d22ba'
down_revision: Union[str, None] = '3458e5ba1dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('power', sa.Integer(), nullable=True))
    op.execute('UPDATE car SET power=160 WHERE power is NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'power')
    # ### end Alembic commands ###
