"""ref_car_steering

Revision ID: aab805cec08b
Revises: 866760fcd31f
Create Date: 2025-10-10 18:57:30.738730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab805cec08b'
down_revision: Union[str, None] = '866760fcd31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('steering', sa.String(), nullable=True, server_default='Правый'))
    op.alter_column('car', 'steering',
                    server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'steering')
    # ### end Alembic commands ###
