"""ref_uniq_ci

Revision ID: c29e33008cb5
Revises: ffbf3c024782
Create Date: 2025-03-10 23:50:52.461156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29e33008cb5'
down_revision: Union[str, None] = 'ffbf3c024782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_image_image_uuid_image_url_car_id_key', 'car_image', type_='unique')
    op.create_unique_constraint(None, 'car_image', ['image_uuid', 'image_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_image', type_='unique')
    op.create_unique_constraint('car_image_image_uuid_image_url_car_id_key', 'car_image', ['image_uuid', 'image_url', 'car_id'])
    # ### end Alembic commands ###
