"""ref_news_review_model_v2

Revision ID: 6f07c5027cf9
Revises: 0a37a2b6ba95
Create Date: 2025-09-16 13:14:45.132567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6f07c5027cf9'
down_revision: Union[str, None] = '0a37a2b6ba95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'created_at',
                    existing_type=sa.DateTime(),
                    server_default=sa.text('now()'),
                    nullable=False)
    op.alter_column('review', 'created_at',
                    existing_type=sa.DateTime(),
                    server_default=sa.text('now()'),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'created_at',
                    existing_type=sa.DateTime(),
                    server_default=None,
                    nullable=False)
    op.alter_column('review', 'created_at',
                    existing_type=sa.DateTime(),
                    server_default=None,
                    nullable=False)
