"""car_img_qniq

Revision ID: ac0aa155b3ab
Revises: 9f2a0e50a87d
Create Date: 2025-03-09 18:56:05.773019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0aa155b3ab'
down_revision: Union[str, None] = '9f2a0e50a87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
