"""ref_uniq_ci_v2

Revision ID: 8539c3167c4e
Revises: 02203b1e2f5d
Create Date: 2025-03-11 00:09:05.614682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8539c3167c4e'
down_revision: Union[str, None] = '02203b1e2f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'main_image')
    op.add_column('car_image', sa.Column('is_main', sa.Boolean(), nullable=True))
    op.drop_constraint('car_image_image_uuid_key', 'car_image', type_='unique')
    op.create_unique_constraint(None, 'car_image', ['image_uuid', 'car_id', 'is_main'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_image', type_='unique')
    op.create_unique_constraint('car_image_image_uuid_key', 'car_image', ['image_uuid'])
    op.drop_column('car_image', 'is_main')
    op.add_column('car', sa.Column('main_image', sa.VARCHAR(length=2083), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
