"""ref_car

Revision ID: 91f431aae0e0
Revises: d34e7eee9639
Create Date: 2025-03-04 08:36:57.227817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91f431aae0e0'
down_revision: Union[str, None] = 'd34e7eee9639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('car', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('car', 'update_at')
    op.drop_column('car', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('car', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('car', 'updated_at')
    op.drop_column('car', 'created_at')
    # ### end Alembic commands ###
