"""ref_news_review_model

Revision ID: 0a37a2b6ba95
Revises: e770f6cc54f3
Create Date: 2025-09-16 13:06:16.206066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a37a2b6ba95'
down_revision: Union[str, None] = 'e770f6cc54f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
