"""ref_car

Revision ID: 65f8784b506d
Revises: b7811aeef387
Create Date: 2025-03-06 23:29:48.355769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f8784b506d'
down_revision: Union[str, None] = 'b7811aeef387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'main_image',
               existing_type=sa.VARCHAR(length=2083),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'main_image',
               existing_type=sa.VARCHAR(length=2083),
               nullable=False)
    # ### end Alembic commands ###
