"""ref_news_model

Revision ID: e770f6cc54f3
Revises: ad6fea3db053
Create Date: 2025-04-12 13:05:47.926634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e770f6cc54f3'
down_revision: Union[str, None] = 'ad6fea3db053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
