"""ref_carImage_ondelete

Revision ID: de5f0c836907
Revises: 5f6b21da84df
Create Date: 2026-03-02 15:27:10.897646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5f0c836907'
down_revision: Union[str, None] = '5f6b21da84df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_image_car_id_fkey', 'car_image', type_='foreignkey')
    op.create_foreign_key(None, 'car_image', 'car', ['car_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_image', type_='foreignkey')
    op.create_foreign_key('car_image_car_id_fkey', 'car_image', 'car', ['car_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
